// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package whtwnd_autogen

// schema: com.whtwnd.blog.defs

import (
	"github.com/bluesky-social/indigo/lex/util"
)

// BlogDefs_BlobMetadata is a "blobMetadata" in the com.whtwnd.blog.defs schema.
type BlogDefs_BlobMetadata struct {
	Blobref *util.LexBlob `json:"blobref" cborgen:"blobref"`
	Name    *string       `json:"name,omitempty" cborgen:"name,omitempty"`
}

// BlogDefs_BlogEntry is a "blogEntry" in the com.whtwnd.blog.defs schema.
type BlogDefs_BlogEntry struct {
	Content   string  `json:"content" cborgen:"content"`
	CreatedAt *string `json:"createdAt,omitempty" cborgen:"createdAt,omitempty"`
}

// BlogDefs_Comment is a "comment" in the com.whtwnd.blog.defs schema.
type BlogDefs_Comment struct {
	Content  string `json:"content" cborgen:"content"`
	EntryUri string `json:"entryUri" cborgen:"entryUri"`
}

// BlogDefs_Ogp is a "ogp" in the com.whtwnd.blog.defs schema.
type BlogDefs_Ogp struct {
	Height *int64 `json:"height,omitempty" cborgen:"height,omitempty"`
	Url    string `json:"url" cborgen:"url"`
	Width  *int64 `json:"width,omitempty" cborgen:"width,omitempty"`
}
