// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package whtwnd_autogen

// schema: com.whtwnd.blog.comment

import (
	"github.com/bluesky-social/indigo/lex/util"
)

func init() {
	util.RegisterType("com.whtwnd.blog.comment", &BlogComment{})
} //
// RECORDTYPE: BlogComment
type BlogComment struct {
	LexiconTypeID string `json:"$type,const=com.whtwnd.blog.comment" cborgen:"$type,const=com.whtwnd.blog.comment"`
	Content       string `json:"content" cborgen:"content"`
	EntryUri      string `json:"entryUri" cborgen:"entryUri"`
}
