// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package whtwnd_autogen

// schema: com.whtwnd.blog.getMentionsByEntry

import (
	"context"

	"github.com/bluesky-social/indigo/xrpc"
)

// BlogGetMentionsByEntry_Output is the output of a com.whtwnd.blog.getMentionsByEntry call.
type BlogGetMentionsByEntry_Output struct {
	Mentions []string `json:"mentions" cborgen:"mentions"`
}

// BlogGetMentionsByEntry calls the XRPC method "com.whtwnd.blog.getMentionsByEntry".
func BlogGetMentionsByEntry(ctx context.Context, c *xrpc.Client, postUri string) (*BlogGetMentionsByEntry_Output, error) {
	var out BlogGetMentionsByEntry_Output

	params := map[string]interface{}{
		"postUri": postUri,
	}
	if err := c.Do(ctx, xrpc.Query, "", "com.whtwnd.blog.getMentionsByEntry", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
