// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package whtwnd_autogen

// schema: com.whtwnd.blog.getAuthorPosts

import (
	"context"

	"github.com/bluesky-social/indigo/xrpc"
)

// BlogGetAuthorPosts_Output is the output of a com.whtwnd.blog.getAuthorPosts call.
type BlogGetAuthorPosts_Output struct {
	Post []*BlogDefs_BlogEntry `json:"post" cborgen:"post"`
}

// BlogGetAuthorPosts calls the XRPC method "com.whtwnd.blog.getAuthorPosts".
func BlogGetAuthorPosts(ctx context.Context, c *xrpc.Client, author string) (*BlogGetAuthorPosts_Output, error) {
	var out BlogGetAuthorPosts_Output

	params := map[string]interface{}{
		"author": author,
	}
	if err := c.Do(ctx, xrpc.Query, "", "com.whtwnd.blog.getAuthorPosts", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
