// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package whtwnd_autogen

// schema: com.whtwnd.blog.notifyOfNewEntry

import (
	"context"

	"github.com/bluesky-social/indigo/xrpc"
)

// BlogNotifyOfNewEntry_Input is the input argument to a com.whtwnd.blog.notifyOfNewEntry call.
type BlogNotifyOfNewEntry_Input struct {
	EntryUri string `json:"entryUri" cborgen:"entryUri"`
}

// BlogNotifyOfNewEntry_Output is the output of a com.whtwnd.blog.notifyOfNewEntry call.
type BlogNotifyOfNewEntry_Output struct {
}

// BlogNotifyOfNewEntry calls the XRPC method "com.whtwnd.blog.notifyOfNewEntry".
func BlogNotifyOfNewEntry(ctx context.Context, c *xrpc.Client, input *BlogNotifyOfNewEntry_Input) (*BlogNotifyOfNewEntry_Output, error) {
	var out BlogNotifyOfNewEntry_Output
	if err := c.Do(ctx, xrpc.Procedure, "application/json", "com.whtwnd.blog.notifyOfNewEntry", nil, input, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
