//go:build exclude
// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package app_autogen

// schema: app.bsky.graph.muteActorList

import (
	"context"

	"github.com/bluesky-social/indigo/xrpc"
)

// GraphMuteActorList_Input is the input argument to a app.bsky.graph.muteActorList call.
type GraphMuteActorList_Input struct {
	List string `json:"list" cborgen:"list"`
}

// GraphMuteActorList calls the XRPC method "app.bsky.graph.muteActorList".
func GraphMuteActorList(ctx context.Context, c *xrpc.Client, input *GraphMuteActorList_Input) error {
	if err := c.Do(ctx, xrpc.Procedure, "application/json", "app.bsky.graph.muteActorList", nil, input, nil); err != nil {
		return err
	}

	return nil
}
