//go:build exclude
// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package app_autogen

// schema: app.bsky.graph.listitem

import (
	"github.com/bluesky-social/indigo/lex/util"
)

func init() {
	util.RegisterType("app.bsky.graph.listitem", &GraphListitem{})
} //
// RECORDTYPE: GraphListitem
type GraphListitem struct {
	LexiconTypeID string `json:"$type,const=app.bsky.graph.listitem" cborgen:"$type,const=app.bsky.graph.listitem"`
	CreatedAt     string `json:"createdAt" cborgen:"createdAt"`
	List          string `json:"list" cborgen:"list"`
	Subject       string `json:"subject" cborgen:"subject"`
}
